spring:
  datasource:
    url: jdbc:h2:file:C:/data/buyer
    #url: jdbc:h2:mem:buyer
    #name: buyer
    username: sa
    password: password
    driverClassName: org.h2.Driver
    #server-po
  h2:
    console.enabled: true
    #server
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



