spring:
  datasource:
    url: jdbc:h2:file:./buyer-a;OLD_INFORMATION_SCHEMA=TRUE #;FILE_LOCK=NO;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update


