spring:
  liquibase:
    change-log: classpath:db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/flightSearcherDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

